### ISSUE TITLE
主界面：显示区域

### ISSUE THREAD

**Issue by SilverBut** [enderdzz/NetworkTask#2]
显示区功能：
- [x] 收发数量展示
  - [x] 收发情况
     比如：白色=未发送 黄色=发送中 绿色=发送完成
  - [x] 窗口位置
     比如：用红边框标注所有黄色区域
  - [x] 保持窗口区域尽量在中央
- [x] 折线图展示
  t（时间）-N（收/发帧数量）展示。两条线。

**Comment by SilverBut** [comment]
直接Canvas算座标 画图

可能要考虑平台兼容性？

**Comment by enderdzz** [comment]
@SilverBut 我这里是Ubuntu14.04环境,gcc 4.8.4,Qt版本3.0.1比较老,canvas不熟悉

**Comment by SilverBut** [comment]
我这里是Qt5……canvas没事，画了个简单的demo。有一些表现和MFC的差别超出了我的想象，不过还勉强在可控范围内。上课我给你看看
